### PR TITLE
Correct filter parameters

### PR DESCRIPTION
**Pull request by drfiemost**
Fixed voice DC and voltage ranges based on circuit simulation:

[8580 voice MDAC](https://www.falstad.com/circuit/circuitjs.html?ctz=CQAgjCAMB0l3AWAnC1b0DYrTAJgMxgYEYIEIDskyFIArJPfY3QKYC0YYAUAEoi4EjfHVwChIBPjGNGEulEUw63AE7jhojQIoyQSeJDUhpjXLpO5Neg-GNCzFhya2NbcewA5HYhN5c2hsamOr5woYoIDB7qzua+-vGR0UaxiRZ0GD7JduqZ2fkBiu5GAO7aSSFJqSCk2brZcinGhUl1EU25IA0RPSKBXe1tEv3FQere2Z7pelFdPUmTHZLNEzMg09ZjXUuL4aNu4-pZEWDUjSs760gn1Zcx4OenTwf6RzfZH0WHXVxWp1YLnMHmcJEk-kDVuBAQD9q43r88NkId8ESCYeCYWAkHp8FkPPwkYw8J5oeF-LJJCwlNgVABlSxbEJSPSMABmAEMADYAZ1Yilw3AZzlGzhZNM5vP5ZiFkn8ov84spkr5AtlhVGhSVihV0oEsvao3a2vZ3NVMoZfS0PRNIF1aoZS1GS1t9otG3lWk2kmkErNesFDK+oy+rv9DseIy0oLkvuV4fdKNGKLDUojRKKGdT5v1AHNtHQEAgCzilHwBJk5cTS35KXJqXXoCpyvhqD6xK3i7WoNxyrhK93O1Wey224PPF2Kb2TBPh-hZ0rp-PJ3JSMOypI192EFu49Odyv6EX19PC4ez+2R0fD8RDxvb8OH4vyk--FQ79P38Ov8-umO3wuU7lBQgGMCBXZ7sBoEbFuQEwYeni7jI06IYeSDHt2G7oWhGGQfoGH+GcggnuURGHmRl4bhR3ZcP+sjTrR5GgpRDHMTRYDQVRHFMQueGCCwx74Hi15XkJWAXmJLEtsJF4IEQIkbnJ4kYfJv5KSJyDKcWik3BpulqbpF50BQWlXsZpnmVJ9AmSJGCVhe972cedlYL+LkiRQMnHhunmmb5Vn+RenjyQ5KEhcewWuXhkUiZ4hneSh8XFnFUXIeUKUiUgNmheUWWmXlVkFReZxOdpDGQKVjwDnhJWmVwXllaRYANeAzWpVe9V1bg4WNdCPV9e1RgAPKPMRnAnFwWjjXWxgUdNo3FuwFKPPiNTYSA83rUtlJnKtxioRtRBuMe80sK2DxbUdC2HScZ3zLO83gRty27Tsa7zQd22KK9Dxfo9D1XXdv0Aycn2A-cG7Ljdq6LYDxh-Vdf0vZAe3qA+j1tqd9DnTUF7zej4N0Dj9jvVdeOE8TaNjVd6PI6jInzXjdNdAe0ObotzMPFDX3c+DP1GMK72KmudZ2gm+oMkzAnaX6aburTjAPqLboS3+HNgW2yvi4G3QPQBMvxnLquff4B1a0bOtbf463mzmOtzYRkDEbbAYMbgiqkmckCkn4HVwD7nv+2WpFB77OIB1e4dyvo7vBzHEcThHG6J9HKf0elvu+yZSefhgEfZ3HBe+3nOcvtM0cl3HlfF970f3rXNekuntQN6Soil-Qse++3cc95nmdN-uA+SL79H8OCeACMRfw0hICDQBQCiNs2w4z5hV4Tx2s4z5D2+T9zcFQ2vhGT4pJ9iIUO+nhNk+FM3l+T+0V8vhIM-tM3T+Tz0z-dP8M89M3b+k8lg-xAcA8IzcwFiG9KA8+HoZrpTgV8H+yDJ5fGbqgsQMZWppUjMSSe2D6LqAzCSMk1YBhUSxKWEk5COru1oTQuu3AgA)

[6581 voice MDAC](https://www.falstad.com/circuit/circuitjs.html?ctz=CQAgjCAMB0l3BWcMBMcUHYMGZIA4UA2ATmIxAUgoqoQFMBaMMAKACcRs0RMVPvsCPlVzx2IACxweGPlJFConeJHES8VXpI2dFIleK6bZk6VqphKcNWZPrjw8FdUd7MvgkIOllsR0-eAbqOotYchFLuILLeFs7iQVoRsU5+0dxaMcFKoS4gyVEFgiEGHBreeDrmqWHpFbaOvrWVFTrFOaUg5VHd7fppxF5RYJCR1U15LVGDKRPiI2MmCwolA0NaM9n9tcwZS2iz8RzLw2B7jUfgB8PXfcppu96PW-c711pn0mDEF2IASlcvmdAVQIkoqJFgVRodAEPNrrsQeAfkoUCgrCwAMr8FY4yRccEgABmAEMADYAZzoqKxplx8nxjiopMp1M0tLc7TcEgJ0OJ5KpNOxQXaQR5TP5rKF+Ui7QK4sJLMF7OxWXaWQVfKVbJ4tN6im6mqU2ulU3aUyNzIFOpQtM27U2lslyt12JO7ROTpNKvAn2yzy91uln1xIcZiqD7IBaDwFGBYAkEjjEsiSD5MDhAHMePgKBhCDnY4RPOCWAB3QvJ5RJhBQ8vVqu4JOa+tNxt4Gt1ivYDvt5u81u92tyMHDqD1iSj4GT-vCCdTjyJquqCsIJdjtez8er9fAwgoTtziv7w-5A-hldn08YUbL+s36+3lsVh9VjBDrvRD98d9by+-qs8AXbcumAoC-3rcCq2IXcjxAGDTwQi96yQscRnPMdL3Q09sOQitcLQhY73wojCKfAcSNvQjvxA5gaLoiCKxjPMC2wbACwQfMQLYjiuJ4vDOHYljJDAXiC0vCRROEySC2fESxMkQZhIkpTONkpS5IkVSuLU5T610gyuLkwyC2LBTLzM4TLLkyzdJwcz7yEuyhLk+zhLwKTdMvDyFJ8gS-N0vBtPEyDgq6DSKPChSyAcisYuE+K5Pi3SRhLLz61ShTMoE5gnK43LZMis5PPylApLk7KUrAPKQpImqrhK2qkQ+bBgXMDLWr4FrgQYdRxwAeWQXMGH4gqQBGoToXmOBYwmgsRmG9FxM4co8h+Wb+PW8alpyVbxA7DahK2uafGIAYUEO+aZvG-iLDO2p80u6JCFmnaRD2so+pOg7tpLd60hep7HpuybkTSYHvq+26wdqQGQdMypfuWnsAeG-i4ZOu60iEJ6vCerHakTJ6cfh07Udxxa-pW7GLtJkmGDe6nCahlyvsZlHrGxImkckL6wC4rVI1dChaYZtLRf55arSlH08Z5uWmAF40hdtbEMZ2jHJYjGXhYhnaIa1wWddVro2ZLH7Fal50bTtUWduOw3leN2kFtektXfGx3pZdW18M68a+tIPhetjS8g4D2Nw8tkCo8Dnq+rD+PI56w2UKTroCRDkC8Ezvqc+D1OK3ziPokULP-zLvqMDLwvS+DvrCBMcv60b+uiyb2vW5LhAUWb1de76nuC4F-SB9jMc+6rLOJ9rie+oVSeF-nzPa6MT3pzBJhPxndeRyTaOJM3xFN13kCT63xd99npcL6vU+LPPW+T09kfj0fxFX1v-9b1vz-a7-4EAEv73l7L-UB-9wHAigsAouR8oFH1fqBK+wIkIwPgjfREqDa5YPjJAd+n5cK30IanAEa9b47S-koVMhIMwsCAA)

Also add a model dependent scaling factor for the output to level out the volumes (#78 and #79)

### CODE REVIEW

**Comment by reFX-Mike** [comment]
Is this pull request a good candidate to be merged soon?

**Comment by drfiemost** [comment]
Nope, it's experimental and in fact breaks digis on the 8580

**Comment by reFX-Mike** [comment]
I implemented these changes three weeks ago and can't reproduce the 8580 issue you mentioned. Could it be that you set the external filter input to 0 instead of some small DC offset?

Can you tell me a couple of test-tunes to use for which you experienced the problem?

**Comment by drfiemost** [comment]
You can try `/MUSICIANS/T/Tel_Jeroen/Turbo_Outrun.sid` forcing the 8580, the digis should be almost silent.

**Comment by drfiemost** [comment]
Yeah there are different kind of digis, some works on both chips other only on the 6581.
Turbo_Outrun requires digiboost on the 8580 but with this patch it becomes loud even without, which is not expected.

Also I realized the voice voltage ranges are halved with respect to the theoretical values so there is something I still don't grasp.

**Comment by reFX-Mike** [comment]
I've reverted this change on my branch as well. Even 6581 digis sounded very uneven. The digi volume varies wildly, even within the same tune. It sounds much better without these experimental changes.

**Pull request closed without merging**
